name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Build frontend
        run: |
          npm install
          npx gulp buildAll

      - name: Build backend and test
        run: |
          chmod +x gradlew
          ./gradlew test bootJar

      - name: Detached run test app
        run: |
          ./gradlew bootRun &

      # Wait up to 30s for the app to start
      - name: Wait for test app start
        run:  |
          export START_TIME=$(date +%s)
          until curl http://localhost:8080/health > /dev/null || test "$(($(date +%s) - $START_TIME))" -gt 30; do sleep 5 | echo "Waiting..."; done
        shell: bash

      - name: Run OpenAPI tests
        run: |
          pip install schemathesis
          schemathesis run --hypothesis-phases=explicit http://localhost:8080/api/v1/energy-labels-openapi.json
